
services:
  hiddify:
    #only for local build and development
    build: .

    #latest release version
    #image: ghcr.io/hiddify/hiddify-manager:latest

    #latest beta version
    #image: ghcr.io/hiddify/hiddify-manager:beta

    #latest build of current development
    # image: ghcr.io/hiddify/hiddify-manager:dev

    #specific version
    #image: ghcr.io/hiddify/hiddify-manager:v10.80.0
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
       - ./docker-data/:/hiddify-data/
    env_file:
      - path: ./docker.env
    #environment:
      #REDIS_PASSWORD used if REDIS_URI_MAIN or REDIS_URI_SSH is not set
      #MYSQL_PASSWORD used if SQLALCHEMY_DATABASE_URI is not set
      #REDIS_URI_MAIN: 'redis://:${REDIS_PASSWORD}@redis:6379/0' 
      #REDIS_URI_SSH: 'redis://:${REDIS_PASSWORD}@redis:6379/1'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqldb://hiddifypanel:${MYSQL_PASSWORD}@mariadb/hiddifypanel?charset=utf8mb4'
    #network_mode: host
    depends_on: 
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    env_file:
      - path: ./docker.env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1       # Root user password
      MYSQL_DATABASE: hiddifypanel             
      MYSQL_USER: hiddifypanel                     
    volumes:
      - ./docker-data/mariadb_data:/var/lib/mysql          # Persistent storage for database files

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    env_file:
      - path: ./docker.env
    command: sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""
    volumes:
      - ./docker-data/redis_data:/data                # Persistent storage for Redis data
    